### ISSUE TITLE
Unity launcher icon to display unread messages?

### ISSUE THREAD

**Issue by orschiro** [Aluxian/Whatsie#105]
Dear @Aluxian,

Would it be possible for Whatsie to display the number of unread messages in the Ubuntu Unity launcher icon?

Sometimes I miss the popping up notification about a new message and thus don't know about a new unread message. 

Do you find this feature useful?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/14733434/4282e642-0863-11e6-9cfc-5d4da3cf393d.png)

**Comment by Aluxian** [comment]
Hey Robert,

I think it's being worked on upstream (on Electron, the framework that Whatsie uses) and I also think it's possible, it's just a matter of time until it'll be implemented.

I'll close this as a duplicate because progress is being tracked here: https://github.com/Aluxian/Whatsie/issues/34

**Comment by orschiro** [comment]
That's great! Thanks for the reference. 

I am sorry that I didn't look for a potential duplicate before...

~Robert
