### ISSUE TITLE
New messages: Show Whatsie NA & flash window

### ISSUE THREAD

**Issue by segelkma** [Aluxian/Whatsie#197]
Hi. Can you add an option to show Whatsie minimized and flash the window in the taskbar when a new message arrives and Whatsie was hidden before?
Thanks for your great program.

**Comment by Aluxian** [comment]
Hey, can you check the latest version? Now it shows a badge with the number of unread notifications (enable from the menu).

**Comment by segelkma** [comment]
Hi, very nice. But the badge will only appear if Whatsie is minimized. If the Whatsiewindow is closed then it will not appear and I sometimes don't see new messages immidiately. Only the tray icon changes color in that case. Would be nice if Whatsiewindow will be shown minimized in that case and gets the badge as well.

Thanks for your work!

**Comment by Aluxian** [comment]
You have Whatsie pinned on your taskbar, right?

The badge will only appear when Whatsie is minimized because if you close the window, Whatsie goes to tray, but the app is not in the taskbar anymore – so it can't show a badge.

So Whatsie can be in the following states:

- window shown, active in the taskbar, tray icon shown -> badges

**Comment by Aluxian** [comment]
You have Whatsie pinned on your taskbar, right?

The badge will only appear when Whatsie is minimized because if you close the window, Whatsie goes to tray, but the app is not in the taskbar anymore – so it can't show a badge.

So Whatsie can be in the following states:

- window shown, shown in the taskbar, tray icon shown -> badges
- window closed, not shown in the taskbar, tray icon shown -> no badges
- window minimized, shown in the taskbar, tray icon shown -> badges

> Would be nice if Whatsiewindow will be shown minimized in that case and gets the badge as well.

For this you have to minimize the window instead of closing it.

The main think to understand is that, when you have an app pinned in the taskbar, the app can either have a window or not. For example, in the following picture:

![](https://i-msdn.sec.s-msft.com/dynimg/IC420541.png)

Notepad is pinned but it doesn't have any windows, so it wouldn't be able to show badges. The calculator app does have an active window, so it could display a badge.

Does what I said make sense?

**Comment by segelkma** [comment]
Yes it does. But its not what I meant :P 
Right now the following happens when Whatsie is closed to tray:
Tray icon is white -> message gets in -> tray icon turns green

What I wish would happen:
Tray icon is white -> message gets in -> tray icon turns green -> automatically show Whatsie minimized and show badge

Would be awesome to have such an option to activate this feature.

**Comment by Aluxian** [comment]
> Yes it does. But its not what I meant :P 

Oh...

Now I get it. So receiving a notification would be like opening the window and immediately minimizing it (without the user seeing it). Hmm.

I think very few people would want this... But I don't like saying no, so I'll mark this as a feature request.

**Comment by segelkma** [comment]
At least in windows this is possible. In the script language AutoIt there is a flag to set a window into minimized not active state. So it will become visible in the taskbar, but the window itself does not show up and it will also (which is important) not get active. So I assume that this must be possible in other programming languages as well since AutoIt often relies on windows functions (see MSDN).

**Comment by Aluxian** [comment]
Hey, after further thinking... I'll have to say no to this feature, I'm sorry.
