### ISSUE TITLE
SSL/Encryption indicator

### ISSUE THREAD

**Issue by amilopowers** [Aluxian/Whatsie#276]
* Operating system: Fedora 23
* Whatsie version: 2.0.15-beta

Hi

Thank you very much for your awesome app!

Could you add an idicator which shows if the connection to the Whatsapp servers is secured over SSL or not? In a traditional browser we can verify that very easy but in Whatsie it isn't possible.

I would also appreciate an indicator which tells if messages really are encrypted properly. I mean to add more Information if the Whisperpush protocol is working.

**Comment by Aluxian** [comment]
Hey!

1. The connection to WhatsApp Web is *always* made through SSL. If you go to http://web.whatsapp.com/, you'll see it won't let you use the http version, either.

2. You can check encryption on your phone, I think. Anyway, I can't add support for that because it's something that WhatsApp's team must add to WhatsApp Web.

Thanks!
