### ISSUE TITLE
make it to be a stand alon app like messenger

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Whatsie#310]
**Description:**
make it to be a stand alon app like messenger

**Operating system:**
OS X, Windows, Linux

**Best thing about Whatsie:**
Performance, Ease of use, Design

**Worst thing about Whatsie:**
nothing

**Extra:**
make an Instagram desktop app

**Comment by TheNLGhost** [comment]
You know this is (almost) not feasible? This is a program that runs through the web application. 
The only two options to make this program standalone is with permission of Whatsapp or by rebuilding this program to make it exactly the same as the phone application, but a really big downside of this is that you can't use Whatsapp on your phone and computer at the same time. Sure, you can switch, but constantly having to revalidate your number because you leave your pc and want to communicate through your phone is really annoying and just not worth it.

**Comment by Aluxian** [comment]
Thanks @TheNLGhost!
