### ISSUE TITLE
Option to password protect execution

### ISSUE THREAD

**Issue by meneses-pt** [Aluxian/Whatsie#4]
It would be very nice if I could password protect the start of whatsie.
This way I could protect myself against "intruders" in my work pc.

**Comment by Aluxian** [comment]
I am going to assume you're referring to Windows.

I will not add this Whatsie because there are dedicated apps for this, see here: http://www.makeuseof.com/tag/how-to-password-protect-any-windows-program/

Note: the app is not released yet, if you downloaded it already please remember it's in beta and some things might not work.

**Comment by meneses-pt** [comment]
I know some things might not work. I have added some other "issues" but in fact I'm just using the suggest feature option in the already available app. These are just suggestions. Feel free to disregard any of my suggestions. ;)
Nice work here BTW.

**Comment by Aluxian** [comment]
Thanks! Can you please join the Gitter channel? I'll upload the beta there for you to test it, after I finish fixing some things (like the windows installer/shortcuts) :)
