### ISSUE TITLE
Ability to disable notification sounds

### ISSUE THREAD

**Issue by meneses-pt** [Aluxian/Whatsie#6]
Right this moment there is no way to disable notification sounds (Windows 10 at least). If you go to System in the Control Panel, and then Notifications and Sounds, you should be able to at least there disable the sounds for a specific app, but Whatsie doesn't show up as an app there.

**Comment by AdrianoCahete** [comment]
Win10 here and Whatsie appears in Sound Mixer

![whatsie_sound](https://cloud.githubusercontent.com/assets/37474/14228034/bc49c96a-f8e0-11e5-8137-2bb38cda4a18.PNG)

**Comment by Aluxian** [comment]
Thanks for the feedback!

So this feature would be redundant on Windows. Linux and OS X, though, don't have "sound mixers" usually. So we either let the users handle this with an app, or find a better way.

Also, since the notification sound is played by Whatsie, if you turn on Do Not Disturb on OS X (which should disable notifications temporarily) Whatsie will still play sounds, which is not ok.



--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Sat, Apr 02, 2016 at 8:40 PM, Adriano Caheté < notifications@github.com [notifications@github.com] > wrote:
Win10 here and Whatsie appears in Sound Mixer

[https://cloud.githubusercontent.com/assets/37474/14228034/bc49c96a-f8e0-11e5-8137-2bb38cda4a18.PNG]

**Comment by AdrianoCahete** [comment]
I don't think it's redundant, but it's a easy way to "Silence" the program.

But i find WhatsApp already have this directly on Options (3 dots):
![whatsie_sound2](https://cloud.githubusercontent.com/assets/37474/14228245/f693b298-f8e5-11e5-8f40-db2cb418ed9c.PNG)

**Comment by Aluxian** [comment]
It does, but on OS X users expect all notifications to be muted when they turn “Do Not Disturb” on, they don’t (want to) think “oh, this app has its own sounds, I have to go in its settings panel too to disable sounds” – and then the same to re-enable them.

-- 
Alexandru Rosianu
Full-Stack Developer
aluxian.com | startersquad.com

On 2 April 2016 at 21:17:12, Adriano Caheté (notifications@github.com) wrote:

I don't think it's redundant, but it's a easy way to "Silence" the program.

But i find WhatsApp already have this directly on Options (3 dots):

**Comment by Aluxian** [comment]
I'll close this in favour of https://github.com/Aluxian/Whatsie/issues/59 since Windows already handles muting and Linux users can use that in-app prefs panel.
